-- JEPX Spot Market Data
CREATE TABLE IF NOT EXISTS jepx_da_price (
    date TEXT,
    slot INTEGER,
    sell_bid_qty_kwh INTEGER,
    buy_bid_qty_kwh INTEGER,
    contract_qty_kwh INTEGER,
    ap0_system DECIMAL(5,2),
    ap1_hokkaido DECIMAL(5,2),
    ap2_tohoku DECIMAL(5,2),
    ap3_tokyo DECIMAL(5,2),
    ap4_chubu DECIMAL(5,2),
    ap5_hokuriku DECIMAL(5,2),
    ap6_kansai DECIMAL(5,2),
    ap7_chugoku DECIMAL(5,2),
    ap8_shikoku DECIMAL(5,2),
    ap9_kyushu DECIMAL(5,2),
    spot_avg_price DECIMAL(5,2),
    alpha_upper_spot_avg_price DECIMAL(5,2),
    alpha_lower_spot_avg_price DECIMAL(5,2),
    alpha_flash_spot_avg_price DECIMAL(5,2),
    alpha_confirmed_spot_avg_price DECIMAL(5,2),
    avoidable_cost_national DECIMAL(5,2),
    avoidable_cost_hokkaido DECIMAL(5,2),
    avoidable_cost_tohoku DECIMAL(5,2),
    avoidable_cost_tokyo DECIMAL(5,2),
    avoidable_cost_chubu DECIMAL(5,2),
    avoidable_cost_hokuriku DECIMAL(5,2),
    avoidable_cost_kansai DECIMAL(5,2),
    avoidable_cost_chugoku DECIMAL(5,2),
    avoidable_cost_shikoku DECIMAL(5,2),
    avoidable_cost_kyushu DECIMAL(5,2),
    sell_block_bid_qty_kwh INTEGER,
    sell_block_contract_qty_kwh INTEGER,
    buy_block_bid_qty_kwh INTEGER,
    buy_block_contract_qty_kwh INTEGER,    
    fip_ref_price_national DECIMAL(5,2),
    fip_ref_price_hokkaido DECIMAL(5,2),
    fip_ref_price_tohoku DECIMAL(5,2),
    fip_ref_price_tokyo DECIMAL(5,2),
    fip_ref_price_chubu DECIMAL(5,2),
    fip_ref_price_hokuriku DECIMAL(5,2),
    fip_ref_price_kansai DECIMAL(5,2),
    fip_ref_price_chugoku DECIMAL(5,2),
    fip_ref_price_shikoku DECIMAL(5,2),
    fip_ref_price_kyushu DECIMAL(5,2),
    PRIMARY KEY (date, slot)
);

CREATE TABLE IF NOT EXISTS jepx_bid_curves (
    id VARCHAR(20) PRIMARY KEY,  -- 20250401_48_1
    date CHAR(8) NOT NULL,       -- YYYYMMDD
    slot INT NOT NULL,           -- 時間帯
    area_code INT NOT NULL,      -- エリアコード
    bid JSON NOT NULL            -- JSON配列形式: 
);

-- Weather Data
CREATE TABLE IF NOT EXISTS jma_weather (
    date DATE,
    hour INTEGER,
    station_id VARCHAR(10),
    temperature DECIMAL(5,2),
    precipitation DECIMAL(5,2),
    PRIMARY KEY (date, hour, station_id)
);

-- TSO全エリア横持ちデータテーブル
CREATE TABLE IF NOT EXISTS tso_data (
    master_key VARCHAR PRIMARY KEY,
    date DATE,
    slot INTEGER,
    "1_area_demand" DOUBLE,
    "1_nuclear" DOUBLE,
    "1_LNG" DOUBLE,
    "1_coal" DOUBLE,
    "1_oil" DOUBLE,
    "1_other_fire" DOUBLE,
    "1_hydro" DOUBLE,
    "1_geothermal" DOUBLE,
    "1_biomass" DOUBLE,
    "1_solar_actual" DOUBLE,
    "1_solar_control" DOUBLE,
    "1_wind_actual" DOUBLE,
    "1_wind_control" DOUBLE,
    "1_pumped_storage" DOUBLE,
    "1_battery" DOUBLE,
    "1_interconnection" DOUBLE,
    "1_other" DOUBLE,
    "1_total" DOUBLE,
    "2_area_demand" DOUBLE,
    "2_nuclear" DOUBLE,
    "2_LNG" DOUBLE,
    "2_coal" DOUBLE,
    "2_oil" DOUBLE,
    "2_other_fire" DOUBLE,
    "2_hydro" DOUBLE,
    "2_geothermal" DOUBLE,
    "2_biomass" DOUBLE,
    "2_solar_actual" DOUBLE,
    "2_solar_control" DOUBLE,
    "2_wind_actual" DOUBLE,
    "2_wind_control" DOUBLE,
    "2_pumped_storage" DOUBLE,
    "2_battery" DOUBLE,
    "2_interconnection" DOUBLE,
    "2_other" DOUBLE,
    "2_total" DOUBLE,
    "3_area_demand" DOUBLE,
    "3_nuclear" DOUBLE,
    "3_LNG" DOUBLE,
    "3_coal" DOUBLE,
    "3_oil" DOUBLE,
    "3_other_fire" DOUBLE,
    "3_hydro" DOUBLE,
    "3_geothermal" DOUBLE,
    "3_biomass" DOUBLE,
    "3_solar_actual" DOUBLE,
    "3_solar_control" DOUBLE,
    "3_wind_actual" DOUBLE,
    "3_wind_control" DOUBLE,
    "3_pumped_storage" DOUBLE,
    "3_battery" DOUBLE,
    "3_interconnection" DOUBLE,
    "3_other" DOUBLE,
    "3_total" DOUBLE,
    "4_area_demand" DOUBLE,
    "4_nuclear" DOUBLE,
    "4_LNG" DOUBLE,
    "4_coal" DOUBLE,
    "4_oil" DOUBLE,
    "4_other_fire" DOUBLE,
    "4_hydro" DOUBLE,
    "4_geothermal" DOUBLE,
    "4_biomass" DOUBLE,
    "4_solar_actual" DOUBLE,
    "4_solar_control" DOUBLE,
    "4_wind_actual" DOUBLE,
    "4_wind_control" DOUBLE,
    "4_pumped_storage" DOUBLE,
    "4_battery" DOUBLE,
    "4_interconnection" DOUBLE,
    "4_other" DOUBLE,
    "4_total" DOUBLE,
    "5_area_demand" DOUBLE,
    "5_nuclear" DOUBLE,
    "5_LNG" DOUBLE,
    "5_coal" DOUBLE,
    "5_oil" DOUBLE,
    "5_other_fire" DOUBLE,
    "5_hydro" DOUBLE,
    "5_geothermal" DOUBLE,
    "5_biomass" DOUBLE,
    "5_solar_actual" DOUBLE,
    "5_solar_control" DOUBLE,
    "5_wind_actual" DOUBLE,
    "5_wind_control" DOUBLE,
    "5_pumped_storage" DOUBLE,
    "5_battery" DOUBLE,
    "5_interconnection" DOUBLE,
    "5_other" DOUBLE,
    "5_total" DOUBLE,
    "6_area_demand" DOUBLE,
    "6_nuclear" DOUBLE,
    "6_LNG" DOUBLE,
    "6_coal" DOUBLE,
    "6_oil" DOUBLE,
    "6_other_fire" DOUBLE,
    "6_hydro" DOUBLE,
    "6_geothermal" DOUBLE,
    "6_biomass" DOUBLE,
    "6_solar_actual" DOUBLE,
    "6_solar_control" DOUBLE,
    "6_wind_actual" DOUBLE,
    "6_wind_control" DOUBLE,
    "6_pumped_storage" DOUBLE,
    "6_battery" DOUBLE,
    "6_interconnection" DOUBLE,
    "6_other" DOUBLE,
    "6_total" DOUBLE,
    "7_area_demand" DOUBLE,
    "7_nuclear" DOUBLE,
    "7_LNG" DOUBLE,
    "7_coal" DOUBLE,
    "7_oil" DOUBLE,
    "7_other_fire" DOUBLE,
    "7_hydro" DOUBLE,
    "7_geothermal" DOUBLE,
    "7_biomass" DOUBLE,
    "7_solar_actual" DOUBLE,
    "7_solar_control" DOUBLE,
    "7_wind_actual" DOUBLE,
    "7_wind_control" DOUBLE,
    "7_pumped_storage" DOUBLE,
    "7_battery" DOUBLE,
    "7_interconnection" DOUBLE,
    "7_other" DOUBLE,
    "7_total" DOUBLE,
    "8_area_demand" DOUBLE,
    "8_nuclear" DOUBLE,
    "8_LNG" DOUBLE,
    "8_coal" DOUBLE,
    "8_oil" DOUBLE,
    "8_other_fire" DOUBLE,
    "8_hydro" DOUBLE,
    "8_geothermal" DOUBLE,
    "8_biomass" DOUBLE,
    "8_solar_actual" DOUBLE,
    "8_solar_control" DOUBLE,
    "8_wind_actual" DOUBLE,
    "8_wind_control" DOUBLE,
    "8_pumped_storage" DOUBLE,
    "8_battery" DOUBLE,
    "8_interconnection" DOUBLE,
    "8_other" DOUBLE,
    "8_total" DOUBLE,
    "9_area_demand" DOUBLE,
    "9_nuclear" DOUBLE,
    "9_LNG" DOUBLE,
    "9_coal" DOUBLE,
    "9_oil" DOUBLE,
    "9_other_fire" DOUBLE,
    "9_hydro" DOUBLE,
    "9_geothermal" DOUBLE,
    "9_biomass" DOUBLE,
    "9_solar_actual" DOUBLE,
    "9_solar_control" DOUBLE,
    "9_wind_actual" DOUBLE,
    "9_wind_control" DOUBLE,
    "9_pumped_storage" DOUBLE,
    "9_battery" DOUBLE,
    "9_interconnection" DOUBLE,
    "9_other" DOUBLE,
    "9_total" DOUBLE
);

-- エリア情報テーブル
CREATE TABLE IF NOT EXISTS tso_areas (
    id INTEGER PRIMARY KEY,
    tso_id VARCHAR UNIQUE,
    name VARCHAR,
    area_code VARCHAR,
    region VARCHAR
);

-- OCCTO Data
CREATE TABLE IF NOT EXISTS occto_interconnection (
    date DATE,
    hour INTEGER,
    line_id VARCHAR(10),
    forecast DECIMAL(10,2),
    actual DECIMAL(10,2),
    PRIMARY KEY (date, hour, line_id)
);

CREATE TABLE IF NOT EXISTS occto_reserve (
    date DATE,
    hour INTEGER,
    area VARCHAR(10),
    reserve_rate DECIMAL(5,2),
    PRIMARY KEY (date, hour, area)
);

-- Futures Data
CREATE TABLE IF NOT EXISTS futures_prices (
    date DATE,
    contract VARCHAR(20),
    price DECIMAL(10,2),
    volume INTEGER,
    exchange VARCHAR(10),
    PRIMARY KEY (date, contract, exchange)
);

-- TSOエリア別データテーブル（1～9）
CREATE TABLE IF NOT EXISTS tso_area_1_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_2_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_3_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_4_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_5_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_6_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_7_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_8_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
);
CREATE TABLE IF NOT EXISTS tso_area_9_data (
    master_key VARCHAR PRIMARY KEY,
    date TEXT,
    slot VARCHAR,
    area_demand DOUBLE,
    nuclear DOUBLE,
    LNG DOUBLE,
    coal DOUBLE,
    oil DOUBLE,
    other_fire DOUBLE,
    hydro DOUBLE,
    geothermal DOUBLE,
    biomass DOUBLE,
    solar_actual DOUBLE,
    solar_control DOUBLE,
    wind_actual DOUBLE,
    wind_control DOUBLE,
    pumped_storage DOUBLE,
    battery DOUBLE,
    interconnection DOUBLE,
    other DOUBLE,
    total DOUBLE
); 